<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Your Name - Portfolio</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
        }
        header {
            background-color: #f4f4f4;
            padding: 20px;
            text-align: center;
        }
        h1, h2 {
            color: #2c3e50;
        }
        .project {
            background-color: #f9f9f9;
            border: 1px solid #ddd;
            padding: 20px;
            margin-top: 20px;
        }
        a {
            color: #3498db;
            text-decoration: none;
        }
        a:hover {
            text-decoration: underline;
        }
    </style>
</head>
<body>
    <header>
        <h1>Your Name</h1>
        <p>Welcome to my portfolio</p>
    </header>

    <main>
        <section id="about">
            <h2>About Me</h2>
            <p>Hello! I'm a [Your Field] student/professional passionate about [Your Interests]. This portfolio showcases some of my recent work and projects.</p>
        </section>

        <section id="projects">
            <h2>Featured Project</h2>
            <div class="project">
                <h3>[Your Project Title]</h3>
                <p>[Brief description of your project and what it demonstrates]</p>
                <ul>
                    <li><a href="path/to/your/project.html">View Project (HTML)</a></li>
                    <li><a href="path/to/your/project.pdf">Download Project (PDF)</a></li>
                    <li><a href="https://github.com/your-username/your-repo/blob/main/your-project-file.extension">View Project on GitHub</a></li>
                </ul>
            </div>
        </section>
    </main>

    <footer>
        <p>© 2024 Your Name. All rights reserved.</p>
    </footer>
</body>
</html>
